name: tappuu_dashboard
description: "Flutter DashBoard."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.0.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15
  path: ^1.8.0
  google_fonts: ^6.2.0
  skeletonizer: ^1.4.2
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  image_picker: ^0.8.7+5
  translator: ^1.0.3+1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.5
  app_links: ^6.4.0
  share_plus: ^10.1.4
  get: ^4.6.7
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_cache_manager: ^3.3.0
  dotted_border: ^2.1.0
  googleapis_auth: ^1.5.0
  flutter_svg: ^2.0.7
  file_picker: ^8.3.7  # تم التحديث هنا
  flutter_colorpicker: ^1.0.3
  html: ^0.15.0
  flutter_html: ^3.0.0
  html_editor_enhanced: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

dependency_overrides:
  collection: ^1.19.0
  path_drawing: ^1.0.0

flutter_native_splash:
  color: "#F2B81B"
  image: "assets/images/play_store_512.png"
  android: true
  ios: true
  web: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  adaptive_icon_background: "#F2B81B"
  adaptive_icon_foreground: "assets/images/play_store_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900