const Map<String, String> enUS = {
  "إنتظر قليلاً...": "Please wait...",
  "إعدادات العملة": "Currency Settings",
  "الليرة السورية": "Syrian Pound",
  "الدولار الأمريكي": "US Dollar",
  "سيتم عرض جميع الأسعار بالعملة المحددة. يمكنك تغييرها في أي وقت.": "All prices will be displayed in the selected currency. You can change it anytime.",
  
  'إضافة إعلان جديد': 'Add New Ad',
  'بيانات المعلن': 'Advertiser Data',
  'سيتم عرض هذه البيانات للتواصل معك': 'This data will be visible for contact',
  'لا توجد بيانات معلن متاحة': 'No advertiser data available',
  'اختر بيانات المعلن': 'Select Advertiser Data',
  'تفاصيل الإعلان': 'Ad Details',
  'عنوان الإعلان': 'Ad Title',
  'وصف الإعلان': 'Ad Description',
  'السعر': 'Price',
  'اختيار التصنيف': 'Select Category',
  'التصنيف الرئيسي': 'Main Category',
  'التصنيف الفرعي': 'Subcategory',
  'التصنيف الثانوي': 'Secondary Subcategory',
  'خصائص الإعلان': 'Ad Features',
  'أدخل': 'Enter',
  'نعم': 'Yes',
  'لا': 'No',
  'صور الإعلان': 'Ad Images',
  'إضافة صور': 'Add Images',
  'لم يتم إضافة أي صور': 'No images added',
  'الموقع الجغرافي': 'Geographical Location',
  'تحديد الموقع الحالي': 'Detect Current Location',
  'الإحداثيات:': 'Coordinates:',
  'اختر المدينة': 'Select City',
  'اختر المنطقة': 'Select Area',
  'نشر الإعلان': 'Publish Ad',
  'أنشئ بياناتك كمعلن': 'Create Your Advertiser Profile',
  'هذه البيانات ستظهر للمستخدمين عند نشر الإعلانات': 'This information will be visible to users when publishing ads',
  'شعار المعلن (اختياري)': 'Advertiser Logo (Optional)',
  'إضافة شعار': 'Add Logo',
  'اضغط على الدائرة لإضافة أو تغيير الشعار': 'Tap the circle to add or change logo',
  'اسم المعلن*': 'Advertiser Name*',
  'أدخل اسمك أو اسم المؤسسة': 'Enter your name or organization',
  'وصف المعلن (اختياري)': 'Advertiser Description (Optional)',
  'أدخل وصفًا مختصرًا عن نشاطك': 'Enter a brief description of your activity',
  'رقم الاتصال*': 'Contact Number*',
  'مثال: 00963XXXXXXXX': 'Example: 00963XXXXXXXX',
  'رقم الواتساب (اختياري)': 'WhatsApp Number (Optional)',
  'مثال: 00963XXXXXXXXXXXXXXXX': 'Example: 00963XXXXXXXXXXXXXXXX',
  'خطأ': 'Error',
  'فشل في حفظ البيانات:': 'Failed to save data:',
  'حفظ البيانات': 'Save Data',
  '* الحقول الإلزامية': '* Required fields',
  'تعديل بيانات المعلن': 'Edit Advertiser Data',
  'قم بتحديث بياناتك ليظهر للمستخدمين بشكل صحيح': 'Update your data to display correctly to users',
  'تغيير الشعار': 'Change Logo',
  'اضغط على الدائرة لتغيير الشعار': 'Tap the circle to change logo',
  'إنشاء حساب جديد': 'Create New Account',
  'انضم إلينا الآن وتمتع بجميع الميزات الحصرية': 'Join us now and enjoy all exclusive features',
  'البريد الإلكتروني': 'Email',
  'رمز التحقق': 'Verification Code',
  'كلمة المرور': 'Password',
  'أدخل بريدك الإلكتروني': 'Enter your email',
  'سيتم إرسال رمز التحقق إلى بريدك الإلكتروني للتأكد من ملكيته': 'A verification code will be sent to your email to confirm ownership',
  'إرسال رمز التحقق': 'Send Verification Code',
  'أدخل رمز التحقق': 'Enter Verification Code',
  'تم إرسال رمز مكون من 6 أرقام إلى ': 'A 6-digit code has been sent to ',
  'لم تستلم الرمز؟': "Didn't receive the code?",
  'إعادة الإرسال': 'Resend',
  'تحقق من الرمز': 'Verify Code',
  'تغيير البريد الإلكتروني': 'Change Email',
  'أنشئ كلمة مرورك': 'Create Your Password',
  'كلمة المرور يجب أن تحتوي على 6 أحرف على الأقل': 'Password must contain at least 6 characters',
  'كلمة المرور صالحة': 'Valid Password',
  'لاحقًا': 'Later',
  'الإنشاء': 'Create',
  'العودة': 'Back',
  'مبروك لقد تم إنشاء حسابك بنجاح': 'Congratulations! Your account has been created successfully',
  'العودة للرئيسية': 'Return to Home',
  'بدء إضافة بيانات المعلن': 'Start Adding Advertiser Data',
  'اضف بيانات المعلن الظاهر للمستخدمين عند نشر الاعلانات\n(الاسم..الشعار(اختياري).رقم الاتصال ورقم الواتساب)': 'Add advertiser data visible to users when publishing ads\n(Name..Logo(optional).Contact number and WhatsApp)',
  'ابحث عن إعلان ...': 'Search for an ad...',
  'ع': 'Urg',
  
  'عاجل': 'Urgent',
  'عرض الإعلانات الجديدة آخر 24 ساعة': 'Show new ads from last 24 hours',
  'الرئيسية': 'Home',
  'البريد': 'Mail',
  'إعداداتي': 'My Settings',
  'خدماتنا': 'Our Services',
  'التصنيفات الرئيسية': 'Main Categories',
  'تسجيل الدخول': 'Login',
  'نسيت كلمة المرور؟': 'Forgot Password?',
  'أو': 'Or',
  'ليس لديك حساب؟': "Don't have an account?",
  'الحقول مطلوبة': 'Fields are required',
  'يرجى ملء جميع الحقول': 'Please fill all fields',
  'نجاح': 'Success',
  'تم تسجيل الدخول': 'Logged in successfully',
  'فشل': 'Failure',
  'خطأ في تسجيل الدخول': 'Login error',
  'لا توجد تصنيفات فرعية': 'No subcategories available',
  'عرض جميع الإعلانات': 'View All Ads',
  "الرجاء الإنتظار قليلاً": "Please wait a moment",
  'الخدمات المتاحة': 'Available Services',
  '١- من نحن': '1- About Us',
  '٢- الشروط والأحكام': '2- Terms & Conditions',
  '٣- الباقات': '3- Packages',
  '٤- آلية إضافة إعلان': '4- Ad Publishing Mechanism',
  '٥- التواصل معنا': '5- Contact Us',
  '٦- الإبلاغ عن مشكلة': '6- Report a Problem',
  'تعديل الإعلان': 'Edit Ad',
  'لا يوجد بيانات للإعلان': 'No ad data available',
  'يتم عرض البيانات الحالية للإعلان. قم بتعديل ما ترغب في تغييره': 'Current ad data is displayed. Modify what you want to change',
  'بدون اسم': 'Unnamed',
  'اعد اختيار اي تصنيف لتظهر الخصائص': 'Re-select any category to show features',
  'القيمة الحالية:': 'Current Value:',
  'إضافة صور جديدة': 'Add New Images',
  'الصور الحالية': 'Current Images',
  'معلومات': 'Information',
  'لا يمكن حذف الصور الحالية من هنا': 'Current images cannot be deleted from here',
  'الصور الجديدة': 'New Images',
  'لم يتم إضافة أي صور بعد': 'No images added yet',
  'تحديث الإعلان': 'Update Ad',
  'ليرة سورية': 'Syrian Pound',
  'تأكيد الحذف': 'Confirm Deletion',
  'هل أنت متأكد من حذف هذا الإعلان؟': 'Are you sure you want to delete this ad?',
  'إلغاء': 'Cancel',
  'حذف': 'Delete',
  'قبل': 'Before',
  'يوم': 'Day',
  'ساعة': 'Hour',
  'دقيقة': 'Minute',
  'مليون': 'Million',
  'ألف': 'Thousand',
  'إعلاناتي': 'My Ads',
  'إعلاناتي المنشورة': 'My Published Ads',
  'لا توجد إعلانات منشورة': 'No published ads',
  'الإعدادات': 'Settings',
  'الإعلانات': 'Ads',
  'إدارة الإعلانات': 'Manage Ads',
  'غير المنشورة': 'Unpublished',
  'حسابي': 'My Account',
  'معلوماتي': 'My Information',
  'تعيين كلمة المرور': 'Set Password',
  'المعلنين': 'Advertisers',
  'إدارة المعلنين': 'Manage Advertisers',
  'إضافة معلن جديد': 'Add New Advertiser',
  'المفضلات': 'Favorites',
  'مفضلاتي من الإعلانات': 'My Favorite Ads',
  'سجل المشاهدات الأخيرة': 'Recent View History',
  'المظهر': 'Appearance',
  'اللغة': 'Language',
  'العملة': 'Currency',
  'تسجيل خروج': 'Logout',
  'حذف الحساب': 'Delete Account',
  'ثيم التطبيق': 'App Theme',
  'تسجيل الخروج': 'Logout',
  'هل أنت متأكد أنك تريد تسجيل الخروج؟': 'Are you sure you want to logout?',
  'هل أنت متأكد أنك تريد حذف حسابك؟ هذه العملية لا يمكن التراجع عنها.': 'Are you sure you want to delete your account? This action cannot be undone.',
  'الأحدث إلى الأقدم': 'Newest to Oldest',
  'الأقدم إلى الأحدث': 'Oldest to Newest',
  'الأغلى إلى الأرخص': 'Highest to Lowest Price',
  'الأرخص إلى الأغلى': 'Lowest to Highest Price',
  'الأكثر مشاهدة': 'Most Viewed',
  'الأقل مشاهدة': 'Least Viewed',
  'ابحث في الإعلانات...': 'Search in ads...',
  'جميع الإعلانات': 'All Ads',
  'طريقة العرض': 'View Mode',
  'الفرز': 'Sort',
  'الفلترة': 'Filter',
  'لا توجد إعلانات مطابقة': 'No matching ads',
  'عرض طولي (مختصر)': 'List View (Compact)',
  'عرض طولي (مفصل)': 'List View (Detailed)',
  'عرض شبكي (مختصر)': 'Grid View (Compact)',
  'عرض شبكي (مفصل)': 'Grid View (Detailed)',
  'خيارات العرض': 'View Options',
  'إغلاق': 'Close',
  'خيارات الفرز': 'Sort Options',
  '1 كم': '1 km',
  '5 كم': '5 km',
  '10 كم': '10 km',
  '20 كم': '20 km',
  '50 كم': '50 km',
  'الخريطة': 'Map',
  'الموقع الجغرافي: غير مدخل': 'Location: Not entered',
  'خط العرض:': 'Latitude:',
  'أخذ الموقع': 'Get Location',
  'حدد نطاق البحث:': 'Set Search Radius:',
  'تطبيق البحث': 'Apply Search',
  "يرجى تحديد الموقع الجغرافي أولاً": "Please set location first",
  'تم البحث في نطاق': 'Searched within',
  'كم': 'km',
  'يجب تسجيل الدخول لإضافة إلى المفضلة': 'Login required to add to favorites',
  'تنبيه': 'Alert',
  'تاريخ النشر:': 'Publish Date:',
  'الخصائص': 'Features',
  'معلومات المعلن': 'Advertiser Info',
  'معلن': 'Advertiser',
  'واتساب': 'WhatsApp',
  'اتصال': 'Call',
  'تعذر فتح واتساب': 'Failed to open WhatsApp',
  'تعذر إجراء المكالمة': 'Failed to make call',
  'غير معروف': 'Unknown',
  'تطبيق الفلترة': 'Apply Filters',
  'إعادة تعيين': 'Reset',
  'الفترة الزمنية': 'Time Period',
  'المنطقة': 'Area',
  'المدينة': 'City',
  'الموقع': 'Location',
  'اختر': 'Select',
  'فلترة الإعلانات': 'Filter Ads',
  'آخر يومين': 'Last 2 Days',
  'آخر أسبوع': 'Last Week',
  'آخر شهر': 'Last Month',
  'آخر سنة': 'Last Year',
  'كل الاوقات': 'All Time',
  'تاريخ التسجيل': 'Registration Date',
  'حالة الحساب': 'Account Status',
  'الإعلانات المجانية': 'Free Ads',
  'مفعل': 'Active',
  'متبقية': 'Remaining',
  'إعدادت اللغة': 'Language Settings',
  'العربية': 'Arabic',
  'ملاحظة': 'Note',
  'تم تغيير اللغة': 'Language changed',
  'ملفات المعلنين': 'Advertiser Profiles',
  'ملفات المعلنين الخاصة بك': 'Your Advertiser Profiles',
  'اختر ملفًا لعرض تفاصيله أو قم بإنشاء ملف جديد': 'Select a profile to view details or create new',
  'إنشاء ملف جديد': 'Create New Profile',
  'لا توجد ملفات متاحة': 'No profiles available',
  'اختر ملف المعلن': 'Select Advertiser Profile',
  'ملف بدون وصف (ID:': 'Unnamed Profile (ID:',
  'ملف المعلن #': 'Advertiser Profile #',
  'معلومات الاتصال': 'Contact Information',
  'رقم الاتصال': 'Contact Number',
  'غير محدد': 'Not specified',
  'تعديل': 'Edit',
  "هل أنت متأكد أنك تريد حذف هذا الملف؟": "Are you sure you want to delete this profile?",
  'المفضلة': 'Favorites',
  'الإعلانات المفضلة': 'Favorite Ads',
  'لا توجد إعلانات في المفضلة': 'No favorite ads',
  'تمت الإزالة': 'Removed',
  'تمت إزالة الإعلان من المفضلة': 'Ad removed from favorites',
  'سجلات البحث': 'Search History',
  'هل أنت متأكد من حذف جميع سجلات البحث؟': 'Are you sure you want to clear all search history?',
  'حذف الكل': 'Clear All',
  'الإعلانات التي شاهدتها': 'Recently Viewed Ads',
  'لا توجد سجلات بحث': 'No search history',
  'تمت إزالة الإعلان من سجلات البحث': 'Ad removed from search history',
 
  'مليون ل.س': 'Million SYP',
  'ألف ل.س': 'Thousand SYP',
  'ل.س': 'SYP',
'معلومات الإعلان': 'Ad Information',
  'مميز': 'Premium',

};